INSERT INTO client (id, name) VALUES
  (1,  'Sakugari'),
  (2,  'BySnoO'),
  (3,  'Ruusskov'),
  (4,  'Lemon Tea'),
  (5,  'Fr29'),
  (6,  'Ashtax'),
  (7,  'Wotop'),
  (8,  'Vadowki'),
  (9,  'Ouah Leouff'),
  (10, 'Abalo'),
  (11, 'YouYou'),
  (12, 'Brqko_x'),
  (13, 'Dess');

INSERT INTO youtube_channel (id, client_id, name, url, position) VALUES
  (1,  1,  'Main channel', 'https://www.youtube.com/@sakuragiaugolem',         0),
  (2,  2,  'Main channel', 'https://www.youtube.com/@BySnoO',                  0),
  (3,  3,  'Main channel', 'https://www.youtube.com/@ruusskov',                0),
  (4,  4,  'Main channel', 'https://www.youtube.com/@lemonteaclashroyale',     0),
  (5,  4,  'Second channel','https://www.youtube.com/@lemonteaclashroyale2',   1),
  (6,  5,  'Main channel', 'https://www.youtube.com/@Fr_29',                   0),
  (7,  6,  'Main channel', 'https://www.youtube.com/@Ashtax',                  0),
  (8,  7,  'Main channel', 'https://www.youtube.com/@Wotop',                   0),
  (9,  8,  'Main channel', 'https://www.youtube.com/@VadowkiSB',               0),
  (10, 9,  'Main channel', 'https://www.youtube.com/@OuahLeouff',              0),
  (11, 10, 'Main channel', 'https://www.youtube.com/@AbaloCoc',                0),
  (12, 11, 'Main channel', 'https://www.youtube.com/@Youyouu',                 0),
  (13, 12, 'Main channel', 'https://www.youtube.com/@Brqko_x',                 0),
  (14, 13, 'Main channel', 'https://www.youtube.com/@Dess2211',                0);
